Update Java Version
PX4/PX4-user_guide pull request #1056
Opened 2021-02-13 17:02 UTC by cdennison

Got this error using Java 14 so updating docs to Java 15

Exception in thread "main" java.lang.UnsupportedClassVersionError: me/drton/jmavsim/Simulator has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 58.0

2021-02-16 22:16 UTC, hamishwillee commented
Thanks @cdennison. 

I've tidied up your suggested "things that need to be fixed". Most of these are translated copies (they automatically get fixed based on the English versions). I'll do some testing.

2021-02-17 01:56 UTC, hamishwillee commented
@julianoes Do you use MacOS and can you test this?

As a test point Ubuntu 20.04 uses Java 14. I just tested against latest PX4 in my VM. It works, though I do get some (different) warnings:
```
BUILD SUCCESSFUL
Total time: 1 second
Options parsed, starting Sim.
Starting GUI...
Feb 16, 2021 4:30:14 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javax.media.j3d.JoglPipeline (rsrc:j3dcore.jar) to method sun.awt.AppContext.getAppContext()
WARNING: Please consider reporting this to the maintainers of javax.media.j3d.JoglPipeline
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  [simulator] Simulator connected on TCP port 4560.
Init MAVLink
INFO  [commander] LED: open /dev/led0 failed (22)
``

2021-02-17 10:32 UTC, julianoes commented
@hamishwillee https://docs.px4.io/master/en/simulation/jmavsim.html#an-illegal-reflective-access-operation-has-occured

2021-02-17 10:33 UTC, julianoes requested changes

2021-02-17 10:33 UTC, julianoes commented on en/dev_setup/dev_env_mac.md
> +You can either download [Java 15 from Oracle](https://www.oracle.com/java/technologies/javase-downloads.html) or use the AdoptOpenJDK tap:
As @hamishwillee says, whatever comes with Ubuntu 20.04 (which is what we're trying to support) should be fine.

2021-02-17 10:33 UTC, julianoes commented on en/dev_setup/dev_env_mac.md
> +brew install --cask adoptopenjdk15
This is fine.

2021-02-17 10:33 UTC, julianoes commented
@cdennison have you tried rebuilding it properly after doing `rm -rf Tools/jMAVSim/out` ?

2021-02-17 22:11 UTC, hamishwillee commented
My take is that we don't change the docs because this should work for either Java and there is no point doing so unless we understand the cause of the actual problem. Any more debugging we might do @julianoes ?

2021-04-07 20:59 UTC, mrpollo commented
fixed by https://github.com/PX4/PX4-user_guide/pull/1095

2021-04-07 20:59 UTC, closed without merging