Update ros1.md
PX4/PX4-user_guide pull request #1249
Opened 2021-05-05 07:53 UTC by potato77

2021-05-05 23:46 UTC, hamishwillee commented
@TSC21 This looks good - any comments/questions before I merge?

2021-05-12 07:07 UTC, hamishwillee commented
@TSC21 ?

2021-05-12 07:16 UTC, TSC21 commented
I don't know the project so I can't really comment on it and neither I have a strong opinion. I just wonder if the idea is to add any similar project that gets created with similar features to this list. My opinion is that this shouldn't be the sort of things we add to the guide, specially because those references are off our control and we don't control their content and quality.

2021-05-13 08:33 UTC, TSC21 commented
@mrpollo tagging you to raise your awareness to the above.

2021-05-13 21:51 UTC, mrpollo commented
Hey @TSC21 and @hamishwillee, this project is by DF Silver Member AMOVLab. They have posted about it numerous times on Slack but never really got much attention. I think they need our help to get it out there to the community, and I think adding it to the documentation is a good first step. I will work with them to promote it to the community.

To be clear, this is a mature project that has gained good adoption within the Chinese community, and they are hoping more developers from other locations take advantage of the open-source packages.

2021-05-13 21:53 UTC, TSC21 commented
> Hey @TSC21 and @hamishwillee, this project is by DF Silver Member AMOVLab. They have posted about it numerous times on Slack but never really got much attention. I think they need our help to get it out there to the community, and I think adding it to the documentation is a good first step. I will work with them to promote it to the community.
> 
> To be clear, this is a mature project that has gained good adoption within the Chinese community, and they are hoping more developers from other locations take advantage of the open-source packages.

Thanks for bringing clarity. Works for me!

2021-05-13 21:53 UTC, TSC21 approved these changes

2021-05-13 21:58 UTC, mrpollo requested changes
I think my version is more concise and brings more clarity into the documentation entry

2021-05-13 21:58 UTC, mrpollo commented on en/ros/ros1.md
> +- [Prometheus Open Source Autonomous Drone Project](https://github.com/amov-lab/Prometheus/blob/master/README_EN.md) - Prometheus is an open source autonomous drone software platform, which provides
```suggestion
- [Prometheus Autonomous Drone Project](https://github.com/amov-lab/Prometheus/blob/master/README_EN.md) - Prometheus is a ROS 1 based, BSD-3 licensed collection of autonomous drone software packages from [AMOVLab](https://github.com/amov-lab), which provides a full set of solutions for the intelligent and autonomous flight of drones, such as mapping, localization, planning, control, and target detection, fully integrated with the Gazebo Simulator.
```

2021-05-13 21:58 UTC, mrpollo commented on en/ros/ros1.md
> +  This project is based on the PX4 Autopilot, and aims to provide PX4 developers with mature airborne computer terminal programs, bringing a more concise and faster development experience.
This sentence is redundant, and I think we can remove it.

2021-05-13 21:58 UTC, mrpollo commented on en/ros/ros1.md
> +  At present, modules such as mapping, localization, planning, control and target detection have been integrated, along with Gazebo simulation.
Let's remove and add the above.

2021-05-13 22:48 UTC, merged

2021-05-13 22:51 UTC, hamishwillee commented
@mrpollo I have accepted your revisions (good) and merged.

@TSC21 Nuno, good questions. FWIW as long as it is clearly separated from the "PX4/core ROS offering" and as long as it is an accurate description (i.e. not "over-marketed") then I have no problem with supporting/enabling technologies like this being linked from our docs. I share your concerns that this might not be all that effective, but as Ramon is working with them to help them out all good with me.