VTOL airspeedless: update parameter names
PX4/PX4-user_guide pull request #3000
Opened 2023-12-21 09:52 UTC by sfuhrer

Required after https://github.com/PX4/PX4-Autopilot/pull/22510

2023-12-21 19:12 UTC, hamishwillee commented on en/config_vtol/vtol_without_airspeed_sensor.md
> +<Badge type="warning" text="Experimental" />
FYI only, I'm experimenting with badges to indicate this kind of thing "as well". I hope to link to a definition at some point.

2023-12-21 19:12 UTC, hamishwillee commented on en/config_vtol/vtol_without_airspeed_sensor.md
> +Examine the throttle level (thrust) when the vehicle is level (no or little pitch and roll), during the ascend (increasing altitude) and when the vehicle is banking (more roll).
FYI only I tend to break on sentences. It's a preference that helps me review the flow of docs when editing, but I also think most comments apply to a sentence, so it's not a bad point to break.

2023-12-21 19:13 UTC, hamishwillee requested changes
This is is awesome, but can you add a release note to https://docs.px4.io/main/en/releases/main.html#vtol ?

2023-12-22 09:43 UTC, sfuhrer commented
> This is is awesome, but can you add a release note to https://docs.px4.io/main/en/releases/main.html#vtol ?

Nice, I wasn't aware of that page, put it on it now. 
It's though not clear if it should fall into the VTOL or FW category, as VTOL and FW share this feature. The same struggle we will have with many MC features, as they also are used on VTOLs. 
Maybe we should put all shared FW/VTOL features into the FW category, and specify that VTOL only covers the custom VTOL features and that also most of the MC and FW changes are important for it.

2023-12-22 23:13 UTC, hamishwillee commented on en/releases/main.md
> +  Added to PX4 in [PX4-Autopilot#22510](https://github.com/PX4/PX4-Autopilot/pull/22510).
```suggestion
- [Simplified airspeed sensor configuration](../config_vtol/vtol_without_airspeed_sensor.md): 
  Replacef parameter `CBRK_AIRSPD_CHK` with [SYS_HAS_NUM_ASPD](../advanced_config/parameter_reference.md#SYS_HAS_NUM_ASPD) and renamed parameter `FW_ARSP_MODE` to [FW_USE_AIRSPD](../advanced_config/parameter_reference.md#FW_USE_AIRSPD).
  To be able to arm without an airspeed sensor set `SYS_HAS_NUM_ASPD` to 0.
  To not use the airspeed sensor data in the controller, set `FW_USE_AIRSPD` to 0.
  Added to PX4 in [PX4-Autopilot#22510](https://github.com/PX4/PX4-Autopilot/pull/22510).
```

2023-12-22 23:23 UTC, hamishwillee commented
> > This is is awesome, but can you add a release note to https://docs.px4.io/main/en/releases/main.html#vtol ?
> 
> Nice, I wasn't aware of that page, put it on it now. It's though not clear if it should fall into the VTOL or FW category, as VTOL and FW share this feature. The same struggle we will have with many MC features, as they also are used on VTOLs. Maybe we should put all shared FW/VTOL features into the FW category, and specify that VTOL only covers the custom VTOL features and that also most of the MC and FW changes are important for it.

Good points. First thing to remember is that the release note structure is not set in stone. If we can generally find a way that captures the broad changes better we can do that. For example, we might always assume everything is vehicle specific, but have a heading "shared features" or similar and use badges or tags to indicate specific vehicles if it is not all of them.

Or we stick with the current structure and add a badge to indicate the supported vehicle types - in this case both vtol and fw?

Second thing, this is FW and VTOL but the document says VTOL and I would not have assumed as a reader it was for FW too. So does this need to be retitled? Is anything else VTOL or FW specific in it? I can work on duplicating in some way if it is truly generic and we have retitled. And again, we can use badges to indicate vehicle types it applies to.

I'm going to merge. Let's continue to discuss here and update this later.

2023-12-22 23:24 UTC, merged

2024-01-08 10:58 UTC, sfuhrer commented
> Good points. First thing to remember is that the release note structure is not set in stone. If we can generally find a way that captures the broad changes better we can do that. For example, we might always assume everything is vehicle specific, but have a heading "shared features" or similar and use badges or tags to indicate specific vehicles if it is not all of them.

We could do:
shared MC/VTOL
shared FW/VTOL
MC specific
FW specific
VTOL specific

> Or we stick with the current structure and add a badge to indicate the supported vehicle types - in this case both vtol and fw?

I'm atm rather in favor of the above, so without badges but with "shared" categories.

> Second thing, this is FW and VTOL but the document says VTOL and I would not have assumed as a reader it was for FW too. So does this need to be retitled? Is anything else VTOL or FW specific in it? I can work on duplicating in some way if it is truly generic and we have retitled. And again, we can use badges to indicate vehicle types it applies to.

Most of that page is as applicable to FW as it is to VTOL, yes. There's a couple of things like transition tuning and quad-chute that ofc is VTOL specific.

2024-01-09 05:38 UTC, hamishwillee commented
Thanks. I've added a note in the airspeedless doc about FW https://github.com/PX4/PX4-user_guide/pull/3014

You're welcome to update the shared FW/VTOL sections when and if you want! I probably won't for now.