Update reference_design.md
PX4/PX4-user_guide pull request #3428
Opened 2024-11-04 12:11 UTC by abisop

# these stm32h7 boards has 1mb ram, not 2mb

2024-11-06 04:10 UTC, hamishwillee commented on en/hardware/reference_design.md
> +- FMUv6: work in progress, final name TBD, variant 6s \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\)
@mrpollo This change is correct "as is".

However we now have 5x, 6, 6s, 6x, 6x-rt. Are the Holybro variants the reference for all of these? E.g. for 6x-RT is it https://docs.px4.io/main/en/flight_controller/pixhawk6x-rt.html ?

Would be good to add those too.

2025-01-23 04:26 UTC, hamishwillee commented on en/hardware/reference_design.md
> +- FMUv6: work in progress, final name TBD, variant 6s \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\)
```suggestion
- FMUv5X: (?REFBOARDNAME) \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\)
- FMUv6X: (?REFBOARDNAME) \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-012%20Pixhawk%20Autopilot%20v6X%20Standard.pdf)
- FMUv6c: (?REFBOARDNAME) \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-018%20Pixhawk%20Autopilot%20v6C%20Standard.pdf))
- FMUv6u: (?REFBOARDNAME) \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-016%20Pixhawk%20Autopilot%20v6U%20Standard.pdf))
- FMUv6X-RT: (Holybro Pixhawk 6X-RT) \(NXP i.MX RT1176, 32 Bit Arm® Cortex®-M7, 1GHz
32 Bit Arm® Cortex®-M4, 400MHz secondary core, 2 MB RAM, 64 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-020%20Pixhawk%20Autopilot%20v6X-RT%20Standard.pdf)
```

2025-01-23 04:35 UTC, hamishwillee commented on en/hardware/reference_design.md
> +- FMUv6X-RT: (Holybro Pixhawk 6X-RT) \(NXP i.MX RT1176, 32 Bit Arm® Cortex®-M7, 1GHz 32 Bit Arm® Cortex®-M4, 400MHz secondary core, 2 MB RAM, 64 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512
@mrpollo I have attempted to update this to match our docs. 
- Can you sanity check the reference board names - e.g. I have assumed that the Holybro variants in each case are the reference
- What is 6U? I can't see a refboard for that? Is the processor info OK?

2025-01-23 15:54 UTC, mrpollo requested changes
Thanks for helping keep this updated, I went ahead and marked a few critical changes that we need before merging. If you can help us get those I would truly appreciate it.

2025-01-23 15:54 UTC, mrpollo commented on en/hardware/reference_design.md
> +- FMUv5X: (Holybro Pixhawk 5X) \(STM32F7, 400 MHz, 512KB RAM, 2 MB flash\)  ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-011%20Pixhawk%20Autopilot%20v5X%20Standard.pdf))
```suggestion
- FMUv5X: (Multiple Products) \(STM32F765, 400 MHz, 512KB RAM, 2 MB flash\)  ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-011%20Pixhawk%20Autopilot%20v5X%20Standard.pdf))
```

2025-01-23 15:54 UTC, mrpollo commented on en/hardware/reference_design.md
> +- FMUv6X: (Holybro Pixhawk 6X) \(STM32H7, 480 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/
```suggestion
- FMUv6X: (Multiple Products) \(STM32H753, 480 MHz, 1 MB RAM, 2 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-012%20Pixhawk%20Autopilot%20v6X%20Standard.pdf))
```

2025-01-23 15:54 UTC, mrpollo commented on en/hardware/reference_design.md
> +- FMUv6c: (Holybro Pixhawk 6C) \(STM32H7, 480 MHz, 1 MB RAM, 2 MB flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-018%20Pixhawk%20Autopilot%20v6C%20Standard.pdf))
```suggestion
- FMUv6C: (Multiple Products) \(STM32H743V, 480 MHz, 1 MB RAM, 2 MB flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-018%20Pixhawk%20Autopilot%20v6C%20Standard.pdf))
```

2025-01-23 15:54 UTC, mrpollo commented on en/hardware/reference_design.md
> +- FMUv6u: (?REFBOARDNAME) \(STM32H7, 400 MHz, 1 MB RAM, 2 MB flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-016%20Pixhawk%20Autopilot%20v6U%20Standard.pdf))
```suggestion
- FMUv6U: (Multiple Products) \(STM32H753, 400 MHz, 1 MB RAM, 2 MB flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-016%20Pixhawk%20Autopilot%20v6U%20Standard.pdf))
```

2025-01-23 15:54 UTC, mrpollo commented on en/hardware/reference_design.md
> +- FMUv6X-RT: (Holybro Pixhawk 6X-RT) \(NXP i.MX RT1176, 32 Bit Arm® Cortex®-M7, 1GHz 32 Bit Arm® Cortex®-M4, 400MHz secondary core, 2 MB RAM, 64 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512
```suggestion
- FMUv6X-RT: (Multiple Products) \(NXP i.MX RT1176, 32 Bit Arm® Cortex®-M7, 1GHz 32 Bit Arm® Cortex®-M4, 400MHz secondary core, 2 MB RAM, 64 MB flash\) and variant 6i \(i.MX RT1050, 600 MHz, 512 KB RAM, external flash\) ([standard](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-020%20Pixhawk%20Autopilot%20v6X-RT%20Standard.pdf))
```

2025-01-23 15:54 UTC, mrpollo commented on en/hardware/reference_design.md
```suggestion

Starting with FMUv5X all new standards are published on GitHub under [Pixhawk/Pixhawk-Standards](https://github.com/pixhawk/Pixhawk-Standards). See [Pixhawk.org](https://pixhawk.org) for more info.

```

2025-01-23 21:32 UTC, hamishwillee approved these changes
Thanks @mrpollo - I merged all those fixes - much appreciated! @abisop Thanks for kicking this off.

2025-01-23 21:33 UTC, hamishwillee approved these changes

2025-01-29 03:42 UTC, merged