Update offboard docs with more details on direct actuator messages
PX4/PX4-user_guide pull request #3470
Opened 2024-11-25 00:03 UTC by qtweng

https://github.com/PX4/PX4-Autopilot/issues/24032

2024-11-27 01:59 UTC, hamishwillee commented
@beniaminopozzan Can you please sanity check this.

2024-12-01 19:41 UTC, beniaminopozzan requested changes
LGTM, just a minor naming adjustment.

2024-12-01 19:41 UTC, beniaminopozzan commented on en/flight_modes/offboard.md
> +  - Currently works at lower level than mixer module. Do not publish these messages when not in offboard mode.
Starting from v1.14, the control_allocator replaced the mixer module
```suggestion
  - Currently works at lower level than then `control_allocator` module. Do not publish these messages when not in offboard mode.
```

2024-12-01 21:23 UTC, hamishwillee approved these changes
Thanks @qtweng and @beniaminopozzan

2024-12-01 21:25 UTC, merged